services:
  - type: web
    name: ai-resume-analytics-app
    env: python
    buildCommand: "pip install -r requirements.txt && cd ai_dashboard && npm install && npm run build && cd .. && cp -r ai_dashboard/dist/* static/"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
